#+TITLE: :ui hl-todo
#+DATE:    February 19, 2017
#+SINCE:   v1.3
#+STARTUP: inlineimages

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#module-flags][Module Flags]]
  - [[#plugins][Plugins]]
- [[#prerequisites][Prerequisites]]
- [[#features][Features]]
  - [[#making-items][Making Items]]
  - [[#keybindings][Keybindings]]
  - [[#adding-items][Adding items.]]
- [[#configuration][Configuration]]
- [[#troubleshooting][Troubleshooting]]

* Description
This module adds syntax highlighting for TODO/FIXME/NOTE tags in programming
major-modes.

** Module Flags
This module provides no flags

** Plugins
+ [[https://github.com/tarsius/hl-todo][hl-todo]]
 
* Prerequisites
This module has no prerequisites

* Features

** Making Items
You can make a TODO item by simply writing
+ =TODO=
  For things that need to be done, just not today.
+ =HACK=
  For tidbits that are unconventional and not intended uses of the
  constituent parts, and may break in a future update.
+ =FIXME=
  For problems that will become bigger problems later if not fixed ASAP.
+ =REVIEW=
  for things that were done hastily and/or hasn't been thoroughly
  tested. it may not even be necessary!
+ =NOTE=
  For especially important gotchas with a given implementation,
  directed at another user other than the author.
+ =DEPRECATED=
  For things that just gotta go and will soon be gone.
+ =BUG=
  For a known bug that needs a workaround
+ =XXX=
  For warning about a problematic or misguiding code

** Keybindings
| keybind   | description                      |
|-----------+----------------------------------|
| =]t=      | go to next TODO item             |
| =[t=      | go to previous TODO item         |
| =SPC p t= | show all TODO items in a project |
| =SPC s p= | search project for a string      |
| =SPC s b= | search buffer for string         |

** TODO Adding items.
The way you would add a TODO item is to use a snippet but these have not been
made. you can make them yourself by adding the snippet to
=$DOOMDIR/snippets/MAJOR-MODE/name-of-snippet=. you will find more info on how
to make them [[https://github.com/hlissner/doom-snippets][here]]

* Configuration
To add your own ITEMS you would need to configure them using
~hl-todo-keyword-faces~
#+BEGIN_SRC emacs-lisp
;; the default
(after! hl-todo
  (setq hl-todo-keyword-faces
        `(
          ("FOO"  . ,(face-foreground "MY COLOUR HEX CODE"))
          ("BAR" . ,(face-foreground 'my-colour-var)))))
#+END_SRC

* TODO Troubleshooting
If you have any problems with this module do get in touch!
