#+TITLE:   os/tty
#+DATE:    August 7, 2020
#+SINCE:   v3.0.0
#+STARTUP: inlineimages nofold

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#maintainers][Maintainers]]
  - [[#module-flags][Module Flags]]
  - [[#plugins][Plugins]]
- [[#prerequisites][Prerequisites]]
- [[#configuration][Configuration]]
- [[#troubleshooting][Troubleshooting]]

* Description
This module configures Emacs for terminal usage.

+ System clipboard integration (through an external clipboard program or OSC-52
  escape codes in supported terminals).
+ Fixes cursor-shape changing across evil states in terminal that support it.
+ Mouse support in the terminal.

** Maintainers
This module has no dedicated maintainers.

** Module Flags
+ =+osx= Instead of piping your kill ring through external programs, like xclip
  or pbcopy, have Emacs emit OSC-52 escape codes instead, allowing Emacs to
  communicate to your clipboard through your terminal. This allows for clipboard
  communication over SSH connections or tmux. However, this requires [[https://github.com/spudlyo/clipetty#terminals-that-support-osc-clipboard-operations][a supported
  terminal]].

** Plugins
+ clipetty
+ evil-terminal-cursor-changer
+ xclip

* Prerequisites
This module has no hard prerequisites, but in order for its features to work you
need

+ For system clipboard integration:
  + A supported clipboard program, such as:
    + Linux: =xclip=, =xsel=, or =wl-clibpoard= (Wayland)
    + macOS: =pbcopy= and =pbpaste= (included with macOS)
    + Windows: =getclip= and =putclip= (cygwin)
  + A terminal that supports OSC 52 escape codes, such as:
    xterm (unix), iTerm2 (macOS), alacritty (cross platform), kitty (macOS, linux), mintty (Windows), hterm (javascript), st (unix), mlterm (cross platform)
+ For cursor shape changing:
  + A terminal that supports VT's DECSCUSR sequence, such as:
    Gnome Terminal, xterm, iTerm (macOS), Konsole, or mintty (Windows).
    Terminal.app (macOS) is supported to, but requires [[http://www.culater.net/software/SIMBL/SIMBL.php][SIMBL]] and [[https://github.com/saitoha/mouseterm-plus/releases][MouseTerm]] Plus
    to work.

* Configuration
# How to configure this module, including common problems and how to address them.

* Troubleshooting
# Common issues and their solution, or places to look for help.
