(source melpa)
(source org)
(source marmalade)
(source gnu)

;; Essentials
(depends-on "cask")
(depends-on "dash")
(depends-on "s")
(depends-on "f")
(depends-on "deferred")
(depends-on "exec-path-from-shell")
(depends-on "use-package")

;; Editing
(depends-on "autopair")
(depends-on "expand-region")
(depends-on "flycheck")
(depends-on "flyspell")
(depends-on "multiple-cursors")
(depends-on "rainbow-delimiters")
(depends-on "autopair")
(depends-on "anzu")
(depends-on "key-chord")
(depends-on "saveplace")
(depends-on "yasnippet")
(depends-on "highlight-indentation" :git "https://github.com/hlissner/Highlight-Indentation-for-Emacs")
(depends-on "git-gutter-fringe")
(depends-on "popwin")
(depends-on "dash-at-point")
(depends-on "auto-complete")
(depends-on "auto-complete-clang")
(depends-on "auto-complete-c-headers")

;; Eeeevil
(depends-on "evil")
(depends-on "evil-matchit")
(depends-on "evil-surround")
(depends-on "evil-numbers")
(depends-on "evil-exchange")
(depends-on "evil-space")
(depends-on "evil-visualstar")
(depends-on "evil-nerd-commenter")

;; Project management
(depends-on "projectile")
(depends-on "helm")
(depends-on "smex")
(depends-on "ag")
(depends-on "grizzl")
(depends-on "neotree")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "flx-ido")

;; Modes/mode-specific
(depends-on "org-plus-contrib")
(depends-on "org-opml" :git "https://github.com/edavis/org-opml")

(depends-on "rainbow-mode")
(depends-on "web-mode")
(depends-on "lua-mode")
(depends-on "php-mode")
(depends-on "emmet-mode")
(depends-on "haml-mode")
(depends-on "scss-mode")
(depends-on "sws-mode")
(depends-on "json-mode")
(depends-on "yaml-mode")
(depends-on "markdown-mode")
(depends-on "glsl-mode")
(depends-on "go-mode" :git "https://github.com/dominikh/go-mode.el")

(depends-on "tern")
(depends-on "tern-auto-complete")

(depends-on "rbenv")
(depends-on "inf-ruby")
(depends-on "ac-inf-ruby")

(depends-on "jedi")

(depends-on "omnisharp")
(depends-on "csharp-mode")
(depends-on "emacs-eclim")

(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
