(source melpa)
(source org)
(source marmalade)
(source gnu)

;; Essentials
(depends-on "cask")
(depends-on "dash")
(depends-on "s")
(depends-on "f")
(depends-on "deferred")
(depends-on "fuzzy")
(depends-on "use-package")
(depends-on "smex")

;; OSX
(depends-on "exec-path-from-shell")
(depends-on "dash-at-point")

;; Core
(depends-on "shut-up")
(depends-on "popwin")
(depends-on "saveplace")
;; (depends-on "key-chord")

;; Editing
(depends-on "smart-mode-line")
(depends-on "dired+")
(depends-on "expand-region")
(depends-on "flycheck")
(depends-on "flyspell")
(depends-on "rainbow-delimiters")
(depends-on "smartparens")
(depends-on "yasnippet")
(depends-on "git-gutter-fringe+")
(depends-on "ace-jump-mode")
;; (depends-on "ace-window")
;; (depends-on "regex-tool")
(depends-on "pcre2el")
(depends-on "emr")
;;(depends-on "smart-forward")
;;(depends-on "multiple-cursors")
;;(depends-on "git-gutter")
;;(depends-on "anzu")
;;(depends-on "smooth-scrolling")

;; Auto-completion
(depends-on "company")
(depends-on "company-c-headers")
(depends-on "company-tern")
;; (depends-on "company-anaconda")
(depends-on "company-inf-ruby")
;;(depends-on "auto-complete")
;;(depends-on "auto-complete-clang")
;;(depends-on "auto-complete-c-headers")
;;(depends-on "ac-etags")
;;(depends-on "ac-ispell")
;;(depends-on "tern-auto-complete")
;;(depends-on "ac-inf-ruby")
;;(depends-on "jedi")


;; Eeeevil
(depends-on "god-mode")
(depends-on "evil")
(depends-on "evil-matchit")
(depends-on "evil-surround")
(depends-on "evil-numbers")
(depends-on "evil-exchange")
(depends-on "evil-space")
(depends-on "evil-visualstar")
(depends-on "evil-indent-textobject")
(depends-on "evil-jumper")
(depends-on "evil-god-state")
;; evil-nerd-commenter chokes if it's installed via cask for some reason...
(depends-on "evil-nerd-commenter")

;; Project management
(depends-on "projectile")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-css-scss")
(depends-on "helm-projectile")
(depends-on "helm-swoop")
(depends-on "helm-company")
(depends-on "neotree")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "flx-ido")
(depends-on "perspective")
(depends-on "persp-projectile")
(depends-on "xcscope")
;;(depends-on "grizzl")

;; Modes/mode-specific
(depends-on "org-plus-contrib")
(depends-on "org-opml" :git "https://github.com/edavis/org-opml")

(depends-on "rainbow-mode")
(depends-on "lua-mode")
(depends-on "php-mode")
(depends-on "haml-mode")
(depends-on "scss-mode")
(depends-on "sass-mode")
(depends-on "sws-mode")
(depends-on "json-mode")
(depends-on "yaml-mode")
(depends-on "markdown-mode")
(depends-on "glsl-mode")
(depends-on "groovy-mode")
(depends-on "swift-mode")
;; (depends-on "haxe-mode")
;; (depends-on "go-mode" :git "https://github.com/dominikh/go-mode.el")

(depends-on "web-mode")
(depends-on "emmet-mode")
(depends-on "web-beautify")

(depends-on "tern")
(depends-on "js2-mode")
(depends-on "js2-refactor")

(depends-on "rspec-mode")
(depends-on "inf-ruby")
(depends-on "robe")

;; (depends-on "anaconda")

(depends-on "omnisharp")
(depends-on "csharp-mode")
(depends-on "emacs-eclim")

(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")

(depends-on "applescript-mode")
(depends-on "cmake-mode")
