#+title:    :lang lean
#+subtitle: For folks with too much to prove
#+created:  September 10, 2019
#+since:    21.12.0 (#1759)

* Description :unfold:
This module adds support for the [[https://leanprover.github.io/about/][Lean programming language]] to Doom Emacs. It supports Lean 4 by default using [[https://codeberg.org/mekeor/nael][nael]], with optional support for Lean 3.

** Maintainers
/This module has no dedicated maintainers./ [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +v3 ::
  Enable legacy support for Lean 3 via [[doom-package:lean-mode]].

** Packages
- [[doom-package:nael]]
- [[doom-package:nael-lsp]] (if [[doom-module::tools lsp]] is enabled)
- [[doom-package:lean-mode]] (if [[doom-module:+v3]] is enabled)

** TODO Hacks
#+begin_quote
 󱌣 This module's hacks haven't been documented yet. [[doom-contrib-module:][Document them?]]
#+end_quote

** TODO Changelog
- *Dec 30, 2025*:
  - Refactored module to support Lean 4 as the primary version using ~nael~.
  - Added ~nael-lsp~ for ~lsp-mode~ integration.
  - Introduced ~+v3~ flag for legacy Lean 3 support via ~lean-mode~.
  - Automatically enabled ~abbrev-mode~ for Lean 4 buffers.

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

#+begin_src elisp
:lang
(lean +v3) ; +v3 is optional for Lean 3 support
#+end_src

** Prerequisites
- **Lean 4**: Requires ~lean4~ and ~lake~ to be installed and available in your ~$PATH~.
- **Lean 3**: If using ~+v3~, requires ~lean3~ and ~leanpkg~.
- **LSP**: It is highly recommended to enable either ~:tools (lsp +eglot)~ (default) or ~:tools lsp~ for a productive environment.

* Usage
** Lean 4 (nael-mode)
By default, opening a ~.lean~ file triggers ~nael-mode~.
- **View Goals**: Press ~<localleader> e~ (~eldoc-doc-buffer~) to see the tactic state and goals.
- **Build Project**: Press ~<localleader> b~ (~project-compile~) to run ~lake build~.
- **Abbreviations**: Lean 4 uses ~abbrev-mode~ for unicode symbols. Press ~<localleader> a~ (~nael-abbrev-help~) to see available abbreviations for the symbol at point.
- **Restart Server**: Press ~<localleader> s r~ to restart the LSP server.

** Lean 3 (lean-mode)
If ~+v3~ is enabled, Lean 3 projects can still use the legacy ~lean-mode~.
- **Toggle Goal**: ~<localleader> g~.
- **Server Commands**: Restart the server with ~<localleader> s r~.

* Configuration
** LSP Client
This module detects which LSP client you have enabled in your ~:tools lsp~ block:
- If ~+eglot~ is enabled, it uses ~eglot~.
- Otherwise, it uses ~lsp-mode~ via the ~nael-lsp~ bridge.

** Customizing nael-mode
You can add your own hooks to ~nael-mode-hook~:
#+begin_src elisp
(add-hook 'nael-mode-hook #'your-favorite-minor-mode)
#+end_src

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-suggest-faq:][Ask one?]]

* TODO Appendix
#+begin_quote
 󱌣 This module has no appendix yet. [[doom-contrib-module:][Write one?]]
#+end_quote