---
name: ðŸ“ Bug Report
description: Report a bug, error, or misbehavior
labels: ["1. bug", "needs-triage"]
body:
- type: markdown
  attributes:
    value: |
      > :warning: **Our issue tracker is for bug reports and feature requests,
      > not configuration questions or requests for help.** Use [our
      > Discord](https://doomemacs.org/discord) for those instead.

      **Before you proceed, please ensure your issue:**

      - Wasn't already reported on [our issue tracker](https://github.com/hlissner/doom-emacs/issues),
      - Hasn't been covered by [our FAQ](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org),
      - Can be reproduced on the **latest commit** of Doom,
      - Is reproducible on Emacs 27 or 28, _(Emacs 29 is not supported!)_
      - Is reproducible in [vanilla Doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox) (i.e. with your private config disabled),
      - Is well-researched using [our troubleshooting guide](https://github.com/hlissner/doom-emacs/blob/master/docs/getting_started.org#troubleshoot).
      - Has not been reported upstream (e.g. in the repos of any involved packages).
- type: textarea
  attributes:
    label: What did you expect to happen?
    placeholder: When I do X, it should do Y.
  validations:
    required: true
- type: textarea
  attributes:
    label: What actually happened?
    description: |
      - Screenshots and gifs are a big help!
      - Check the \*Messages\* buffer for errors and/or warnings (press `C-h e` to view this buffer).
      - **Always include backtraces for errors.** ([How to produce a backtrace](https://github.com/hlissner/doom-emacs/blob/master/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error))
      - **Use [code fences](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) for code, logs, or text dumps!** Or use pastebin.com!
      - Be specific! Phrases like "X does not work" or "X stopped working" are unacceptable.
    placeholder: |
      When I do X, Z happened. Here is the backtrace:

      ```
      Debugger entered--Lisp error: (error "Beep Boop")
        error("Beep Boop")
        pp-eval-expression((error "Beep Boop"))
        \#<subr funcall-interactively>(pp-eval-expression (error "Beep Boop"))
        apply(#<subr funcall-interactively> (pp-eval-expression (error "Beep Boop")))
        funcall-interactively(pp-eval-expression (error "Beep Boop"))
      ```

      And here is the log: https://pastebin.com/fakeurl
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your attempts to resolve the issue
    description: |
      How have you tried to fix your issue? What was the result?

      _(Hint: use [code fences](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) for code or text dumps!)_
    placeholder: |
      I tried setting X to Y, then I tried Z. Here's what else I tried...

      ```elisp
      (setq variable value)
      ```
- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      How do we reproduce your issue? Walk us through a minimal test case.

      > :warning: This is required! If you can't offer steps to reproduce it, the issue will be immediately closed!
    placeholder: |
      1. Open Emacs
      2. `M-x doom/info` and be prompted to visit pastebin.com
      3. Press `y` to open pastebin.com in browser
      4. Paste the contents of my clipboard into text box
      5. Click "Create New Paste"
      6. My wife leaves me
  validations:
    required: true
- type: input
  id: doominfo
  attributes:
    label: System Information
    description: |
      Provide a [pastebin.com](https://pastebin.com) link to the output of `M-x doom/info` or `$ ~/.emacs.d/bin/doom info`.

      > :warning: **This _must_ be a pastebin.com link.** Please don't use any other service, please don't paste your doom-info directly into this box, and please don't omit it. If you can't provide it, **please explain why in the box below or other fields above!**
    placeholder: https://pastebin.com/fakeurl
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Please take a moment to ensure your issue (and it's title) is **well-researched, descriptive, and specific**, otherwise, you risk it being significantly delayed or automatically closed.

      Emacs' complexity and extensibility produces many false positive or vague bug reports, so I will immediately close issues that aren't **actionable**, **reproducible in vanilla Doom**, or able to be investigated in a **reasonable amount of time**.

      If you don't think your issue qualifies, please bring it up on [our Discord](https://doomemacs.org/discord) instead.

      :heart: **Thank you for taking the time to file this bug report!**
