---
name: 📦 Update Package
description: Request a pinned package be bumped
labels: ["1. update", "needs-triage"]
body:
- type: markdown
  attributes:
    value: |
      Doom pins its packages to certain commits to avoid breaking updates and to help its maintainer keep up with changes. These pins are updated (bumped) frequently, usually every other week, but some may warrant an early bump, due to critical bug fixes or to adapt to external events.

      Use this form to let us know about these packages.

      -----

      **Before you submit this bump request, make sure...**

      + [ ] To search for any open (or closed) [bump requests for this package](https://github.com/hlissner/doom-emacs/pulls?q=is%3Apr+is%3Aopen+label%3A%221.+update%29%22+).
      + [ ] The target package(s) **are not** in [the do-not-PR list](https://gist.github.com/hlissner/bb6365626d825aeaf5e857b1c03c9837) list.
      + [ ] These packages haven't already been bumped on the [latest commit of Doom](https://github.com/hlissner/doom-emacs/commit).
      + [ ] The new versions of these packages work without issue.
- type: textarea
  attributes:
    label: What package(s) should be bumped?
    placeholder: |
      lsp-mode, lsp-python-ms, lsp-pyright, ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Why should Doom bump these packages early?
    description: |
      Briefly describe what has changed, and why they warrant an early bump. Link any relevant commits or issues, if possible. Mention anything Doom may have to change to accommodate it.
    placeholder: |
      Recent changes to X have fixed several open issues in Y and Z, but have broken A and B in Doom.
