---
name: ðŸ“ Feature Request
description: Propose a new idea or feature
labels: ["1. request", "needs-triage"]
body:
- type: markdown
  attributes:
    value: |
      > :warning: **Our issue tracker is for bug reports and feature requests, not configuration questions or requests for help.** Use [our Discord](https://doomemacs.org/discord) for those instead.

      **Before you proceed, please ensure your request:**

      - Is a feature request and not a bug report,
      - Hasn't already been requested or reported on [our issue tracker](https://github.com/hlissner/doom-emacs/issues),
      - Hasn't already been fulfilled on the latest version of Doom or in [one of our modules](https://git.doomemacs.org/docs/modules.org).
- type: textarea
  attributes:
    label: Describe your request
    placeholder: |
      I'd like Doom to incorporate the game, Doom Eternal, into Doom Emacs, [found here](https://store.steampowered.com/app/379720/DOOM/).

      It replaces `M-x doctor` with a superior alternative: a distraction from your personal problems.
  validations:
    required: true
- type: textarea
  attributes:
    label: Briefly explain its use-case
    description: |
      How would your requested feature be used? Can you demonstrate it with a screencast of another editor? List the steps a typical user would take to use it, were it added to Doom.
    placeholder: |
      1. Install Linux
      2. Install Emacs
      3. Install Doom
      4. Install Doom Eternal
      5. Speed run Doom Eternal
      6. Ponder why your wife left you
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Please take a moment to ensure your feature request (and it's title) is **well-researched, descriptive, and specific**, otherwise, you risk it being significantly delayed or automatically closed.

      Emacs' complexity and extensibility produces many false positive or vague requests, so I will immediately close issues that aren't **actionable**, **poorly explained**, or able to be investigated in a reasonable amount of **time**.

      If you don't think your request qualifies, please bring it up on [our Discord](https://doomemacs.org/discord) instead.

      :heart: **Thank you for taking the time to make this feature request!**
