#+TITLE:   checkers/grammar
#+DATE:    January 9, 2020
#+SINCE:   v3.0.0
#+STARTUP: inlineimages nofold

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#maintainers][Maintainers]]
  - [[#module-flags][Module Flags]]
  - [[#plugins][Plugins]]
- [[#prerequisites][Prerequisites]]
- [[#features][Features]]
  - [[#language-tool][Language Tool]]
    - [[#commands][Commands]]
  - [[#writegood-mode][writegood-mode]]
- [[#configuration][Configuration]]
- [[#troubleshooting][Troubleshooting]]

* Description
This module adds grammar checking to Emacs to aid your writing by combining
=lang-tool= and =writegood-mode=.

** Maintainers
This module has no dedicated maintainers.

** Module Flags
This module provides no flags.

** Plugins
+ [[https://github.com/mhayashi1120/Emacs-langtool][langtool]]
+ [[https://github.com/bnbeckwith/writegood-mode][writegood-mode]]

* Prerequisites
This module requires langtool (which requires =Java 1.8+=).

It can be acquired either from https://languagetool.org/ or your OS's package
manager:

+ macOS: ~brew install languagetool~
+ Arch Linux: ~pacman -S languagetool~

This module tries to guess the location of languagetool-commandline.jar. If you
get a warning that Doom =couldn't find languagetool-commandline.jar=, you will
need to set ~langtool-language-tool-jar~ to its location.

* Features
An in-depth list of features, how to use them, and their dependencies.

** Language Tool
[[https://www.languagetool.org/][Language Tool]] is a polyglot proofreader service that checks for grammar and
stylistic issues in your writing. This requires Java 1.8+.

#+begin_quote
This requires Java 1.8+
#+end_quote

*** Commands
- ~langtool-check~
- ~langtool-correct-buffer~

** writegood-mode
This minor mode highlights weasel words, duplication and passive voice.

* Configuration
How to configure this module, including common problems and how to address them.

* Troubleshooting
Common issues and their solution, or places to look for help.
