#+TITLE:   ui/window-select
#+DATE:    October 8, 2017
#+SINCE:   v2.0.7
#+STARTUP: inlineimages

* Table of Contents :TOC:
- [[#description][Description]]
  - [[#module-flags][Module Flags]]
  - [[#packages][Packages]]
- [[#prerequisites][Prerequisites]]
- [[#features][Features]]
- [[#configuration][Configuration]]
  - [[#ace-window][ace-window]]
  - [[#switch-window][switch-window]]

* Description
This module provides the user with a visual way to switch windows. By default,
the module only kicks in if there are more than two windows open at the same
time.

** Module Flags
+ =+switch-window= Use the switch-window package as the backend.
+ =+ace-window= Use avy (i.e. ace-window) as the backend.

If neither flag is specified, ~+ace-window~ is implied.

** Packages
+ switch-window (if =+switch-window=)
+ ace-window (if =+ace-window= or no flags)

* Prerequisites
This module has no additional dependencies.

* Features
This module remaps the function ~other-window~ to either ~switch-window~ or
~ace-window~, depending on which backend you've enabled.

~other-window~ is bound to ~C-x o~ and ~SPC w o~.

* Configuration
This module provides two backends, both providing the same functionality, but
with different visual cues. They are =ace-window= and =switch-window=.

** ace-window
The first character of the buffers changes to a highlighted, user-selectable
character.

 + Pros: the content of the buffers are always visible.
 + Cons: The displayed characters are small and difficult to see.

** switch-window
Replaces the entire buffer with large letters.

 + Pros: The displayed characters are /really/ easy to see.
 + Cons: You can't see the contents of the buffers.
