#+TITLE:   lang/julia
#+DATE:    April 8, 2020
#+SINCE:   {replace with next tagged release version}
#+STARTUP: inlineimages nofold

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#module-flags][Module Flags]]
  - [[#plugins][Plugins]]
- [[#prerequisites][Prerequisites]]
  - [[#language-server][Language Server]]
    - [[#lsp-julia][~lsp-julia~]]
    - [[#eglot-jl][~eglot-jl~]]
- [[#features][Features]]
  - [[#language-server-1][Language Server]]
- [[#configuration][Configuration]]
  - [[#language-server-lsp][Language server (~+lsp~)]]

* Description
Adds Julia support to Doom Emacs

+ Syntax highlighting and latex symbols from ~julia-mode~
+ REPL integration from ~julia-repl~
+ Code completion and syntax checking, requires ~:tools lsp~ and ~+lsp~

** Module Flags
+ =+lsp= Language Server Protocol support
** Plugins
+ [[https://github.com/tpapp/julia-repl][julia-mode]]
+ [[https://github.com/JuliaEditorSupport/julia-emacs/][julia-repl]]
+ =+lsp= and =:tools lsp=
  + [[https://github.com/non-jedi/lsp-julia][lsp-julia]]
  + [[https://github.com/emacs-lsp/lsp-mode][lsp]]
+ =+lsp= and =:tools lsp +eglot=
  + [[https://github.com/non-jedi/eglot-jl][eglot-jl]]
  + [[https://github.com/joaotavora/eglot][eglot]]

* Prerequisites
This module has no direct prerequisites.

** Language Server
~+lsp~ requires ~LanguageServer.jl~ and ~SymbolServer.jl~. To install these,
execute the following in a Julia REPL.

#+BEGIN_SRC julia
using Pkg
Pkg.add("LanguageServer")
Pkg.add("SymbolServer")
#+END_SRC

More specific notes depend on whether you use ~lsp-julia~ (~:tools lsp~) or
~eglot-jl~ (~:tools lsp +eglot~).

*** ~lsp-julia~
Alternatively, you can use the version of ~LanguageServer.jl~ and dependencies
bundled by ~lsp-julia~. Try this if the former method doesn't work because
~lsp-julia~ is not compatible with every version of ~LanguageServer.jl~. To
use the bundled language server, put the following in your personal ~packages.el~
and ~config.el~, respectively.

#+BEGIN_SRC elisp
;; ~/.doom.d/packages.el
(package! lsp-julia)
;; ~/.doom.d/config.el
(after! straight
  (setq lsp-julia-package-dir (concat straight-base-dir "straight/repos/lsp-julia/languageserver/")))
#+END_SRC

*** ~eglot-jl~
To find your installation of ~LanguageServer.jl~, ~eglot-jl~ needs to know the
environment in which it is installed. This is set to v1.0 by default as it is
the current LTS.

#+BEGIN_SRC elisp
;; ~/.doom.d/config.el
(setq eglot-jl-language-server-project "~/.julia/environments/v1.0")
#+END_SRC

Alternatively, you can let ~eglot-jl~ handle the installation of
~LanguageServer.jl~ and its dependencies by putting the following in your
personal ~config.el~.

#+BEGIN_SRC elisp
;; ~/.doom.d/config.el
(setq eglot-jl-language-server-project (eval (car (get 'eglot-jl-language-server-project 'standard-value))))
#+END_SRC

* Features
  # An in-depth list of features, how to use them, and their dependencies.
** Language Server
~+lsp~ adds code completion, syntax checking, formatting and other ~lsp-mode~
or ~eglot~ features. It requires ~LanguageServer.jl~, the installation of which
is described above.

* Configuration
** Language server (~+lsp~)
~lsp-julia~ requires a variable be set for the Julia environment. This is set to
v1.0 by default as it is the current LTS.

#+BEGIN_SRC elisp
;; ~/.doom.d/config.el
(setq lsp-julia-default-environment "~/.julia/environments/v1.0")
#+END_SRC
