#+TITLE:   lang/julia
#+DATE:    April 8, 2020
#+SINCE:   {replace with next tagged release version}
#+STARTUP: inlineimages nofold

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#module-flags][Module Flags]]
  - [[#plugins][Plugins]]
- [[#prerequisites][Prerequisites]]
- [[#features][Features]]
  - [[#language-server][Language Server]]
- [[#configuration][Configuration]]

* Description
Adds Julia support to Doom Emacs

+ Syntax highlighting and latex symbols from ~julia-mode~
+ REPL integration from ~julia-repl~
+ Code completion and syntax checking, requires ~:tools lsp~ and ~+lsp~

** Module Flags
+ =+lsp= Language Server Protocol support
** Plugins
+ [[https://github.com/tpapp/julia-repl][julia-mode]]
+ [[https://github.com/JuliaEditorSupport/julia-emacs/][julia-repl]]
+ =+lsp= and =:tools lsp=
  + [[https://github.com/non-jedi/lsp-julia][lsp-julia]]*
  + [[https://github.com/non-jedi/eglot-jl][eglot-jl]]*
  + [[https://github.com/emacs-lsp/lsp-mode][lsp]]

* Prerequisites
This module has no direct prerequisites.

Because ~lsp-julia~ and ~eglot-jl~ when first used install julia packages,
temporarily setting the lsp timeout (~lsp-julia-timeout~ or ~eglot-connect-timeout~)
to a large value is necessary.

* Features
  # An in-depth list of features, how to use them, and their dependencies.
** Language Server
~+lsp~ adds code completion, syntax checking, formatting and other ~lsp-mode~
features.
~+lsp~ uses either ~lsp-julia~ when using ~lsp-mode~ or ~eglot-jl~ when using
~eglot~ to provide ~LanguageServer.jl~ with its dependencies.

* Configuration
~lsp-julia~ requires a variable be set for the Julia environment. This is set to
v1.0 by default as it is the current LTS.

#+BEGIN_SRC elisp
;; ~/.doom.d/config.el
(setq lsp-julia-default-environment "~/.julia/environments/v1.0")
#+END_SRC

~eglot-jl~ automatically sets the Julia environment.

If you would like to use your own installation of ~LanguageServer.jl~, put the
following in your personal ~config.el~.

#+BEGIN_SRC elisp
;; ~/.doom.d/config.el
;; lsp-julia
(setq lsp-julia-package-dir nil)
;; eglot-jl
(defcustom eglot-jl-language-server-project "/path/to/project")
#+END_SRC
