#+title:    :lang flix
#+subtitle: scala + ocaml + haskell
#+created:  Jul 1, 2024
#+since:    29.03.0

* Description :unfold:
This module adds [[https://flix.dev/][flix programming language]] support to Doom Emacs. It uses a slighly customized version of [[https://github.com/jhckragh/flix-mode][flix-mode.el]] for syntax highlighting. The module allows for flix commands to be run via the *flix.jar* that flix projects use to run code. It also adds REPL support for flix, allowing the user to create and interact with the REPL.

** Maintainers
*This module needs a maintainer.* [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
/This module has no flags./

** Packages
/This module has no packages./

** Hacks
/No hacks documented for this module./

* TODO Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

* TODO Usage
#+begin_quote
 󱌣 This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Configuration
#+begin_quote
 󱌣 This module has no configuration documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-suggest-faq:][Ask one?]]

* TODO Appendix
#+begin_quote
 󱌣 This module has no appendix yet. [[doom-contrib-module:][Write one?]]
#+end_quote
