name: 'Auto-label Issues/PRs'
on:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    name: labeler
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - uses: actions/labeler@main
        with:
          repo-token: ${{ github.token }}
      # - name: Synchronize labels
      #   uses: julb/action-manage-label@v1
      #   with:
      #     from: .github/labels.yml
      #     skip_delete: false
